fix: false
parallel: true

ignore:
  - 'vendor/**/*'
  - 'spec/**/*':
    # There are some false hits when doing repeated
    # Class.new blocks in different test cases
    - Lint/DuplicateMethods
    # This was causing many tests to be harder to read.
    # Ongoing discussion with StandardRB team in
    # https://github.com/testdouble/standard/issues/94
    - Standard/SemanticBlocks