sudo: false
language: ruby
rvm:
  - 2.3.3

script: "bundle exec rake"

install: bundle install --retry=3 --jobs=3

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: graphiti
  on:
    tags: true
    repo: graphiti/graphiti
